{% set data = load_setup_py_data() %}

package:
  name: kite
  version: {{ data.get('version') }}

source:
  path: kite.git/
  # git-url: https://github.com/pyrocko/kite

requirements:
  build:
    - python
    - numpy
  run:
    - pyrocko
    - python
    - numpy
    - scipy
    - pyqt
    - pyqtgraph
    - matplotlib
    - utm

# test:
#   script_files:
#     - test
#   requires:
#     - nose
#   imports:
#     - kite
#   commands:
#     - nosetests --verbosity=2 --detailed-errors test

about:
  home: https://pyrocko.org
  license: GPL3
  license-family: GPL
  summary: Tools for InSAR displacement processing and modelling.
  doc_url: https://pyrocko.org/docs/kite
